### ISSUE TITLE
On Windows Intellij IDE's don't recognize the font as monospaced

### ISSUE THREAD

**Issue by hesselmonk** [0xType/0xProto#68]
To be able to select the 0xProto font in Intellij IDE's (Rider in this case), I have to disable the "Show only monospaced fonts" checkbox

![image](https://github.com/0xType/0xProto/assets/28805623/b8c16a89-5918-4b6a-9252-41cc39e0a2b9)

Maybe it is related to the missing meta data (https://github.com/0xType/0xProto/issues/67#issuecomment-2064004495)

**Comment by masaakim** [comment]
@hesselmonk  Could you try with this font file? [0xProto-Regular-next.zip](https://github.com/0xType/0xProto/files/15032298/0xProto-Regular-next.zip)

This file contains the changes for the upcoming release, including the removal of zero-width glyphs (e.g., U+200B). Since all glyphs in this font file have the same width, it will be classified as a monospaced font.

**Comment by hesselmonk** [comment]
Using that font file does not seem to make a difference, it is still not in the monospaced font list. This might, again, be an Intellij specific issue because other applications (such as the Windows Terminal) do recognize it as monospace.

I see that Jetbrains own font is also made using Glyphs, maybe there's some useful info in their settings? https://github.com/JetBrains/JetBrainsMono

**Comment by masaakim** [comment]
I found a bug ( https://github.com/0xType/0xProto/issues/69 ) in the current version where some glyphs are wider than others and are no longer strictly monospaced font.
I've fixed it in the v2.0 Pull Request ( https://github.com/0xType/0xProto/pull/66 ), so perhaps this problem will be fixed at the same time.

**Comment by masaakim** [comment]
@hesselmonk Could you try to use 0xProto [v2.000](https://github.com/0xType/0xProto/releases/tag/2.000)? It includes the change to fix the bug in this comment https://github.com/0xType/0xProto/issues/68#issuecomment-2072109024

**Comment by hesselmonk** [comment]
Sadly Rider still doesn't list it as monospace on Windows (I installed the ttf font)

**Comment by masaakim** [comment]
I see. Thanks for letting me know.

**Comment by tebowy** [comment]
Not sure if it's JetBrains' fault but it doesn't find the OTF build at all 

![Image](https://github.com/user-attachments/assets/8bf3da47-d1bf-4738-9564-a6d3dd1ebb84)

**Comment by matype** [comment]
@tebowy Is it only 0xProto that can't use OTF fonts? Or are other fonts also affected?

**Comment by tebowy** [comment]
@matype ah, yeah, jetbrains doesn't load other OTFs either. Sorry about brining yours up. I'll try to rename the TTF font so that it does not collide with OTF one.

**Comment by silvinor** [comment]
[Clue, maybe]

FontForge shows the OS/2 PFM Family as Decorative - should this not be monospace ?

![Image](https://github.com/user-attachments/assets/e375f4b7-b931-49d0-a138-59432aae9254)

Not really an IntelliJ user - but this helped with older windows command prompt stuff.

**Comment by matype** [comment]
I've just released [v2.400](https://github.com/0xType/0xProto/releases/tag/2.400). 

Can anyone confirm if the problem with this issue has been resolved?

**Comment by tebowy** [comment]
@matype  Yes, for both 0x and Zx prefixes, at least on macOS. I'll reply later with Windows results.

**Comment by msaktype** [comment]
Just released [v2.502](https://github.com/0xType/0xProto/releases/tag/2.502) that includes changes to pass [Font Bakery](https://fontbakery.readthedocs.io/) `check-universal`.
`fontbakery check-universal` is [checks for best practices agreed upon on the type design community](https://fontbakery.readthedocs.io/en/latest/user/USAGE.html#fontbakery-check-universal).

@hesselmonk Could you use the latest 0xProto and check to fix this issue?

**Comment by wazedde** [comment]
The not-showing-up-as-monospace-font issue has not been an issue for some time anymore. At least on my Windows systems.

As for the font not showing up at all for users, that seems to be a different issue that is Jetbrains related where you have to install a font globally for all users. Otherwise it will not show up. [issue](https://stackoverflow.com/questions/57216846/font-is-installed-but-doesnt-show-in-the-menu-of-jetbrains-intellij-idea)

<img width="1229" height="896" alt="Image" src="https://github.com/user-attachments/assets/52c4d805-dfb0-4652-a26a-6b98642c3db0" />

<img width="688" height="398" alt="Image" src="https://github.com/user-attachments/assets/47ca7ed9-fbde-40dc-a1a3-093d29d08786" />

**Comment by msaktype** [comment]
@jakkovanhunen Thank you for confirming!

I will close this issue. If it is still unresolved, please reopen it.
